### ISSUE TITLE
Unknown function: NERDTreeAddMenuItem

### ISSUE THREAD

**Issue by coot** [markgandolfo/nerdtree-fetch.vim#1]
Even though I have NERDTree I got the error:
Unknown function: NERDTreeAddMenuItem
The function exists after vim is loaded.  As a workaround I'd suggest to put the plugin in after/plugin directory then it will be loaded after NERDTree.

**Comment by MarkOates** [comment]
The proper solution is to ensure that your plugins are listed in the correct order in your `~/.vimrc` file. This will reproduce the error:

```vim
Plugin 'markgandolfo/nerdtree-fetch'
Plugin 'scrooloose/nerdcommenter'
```

while the correct ordering will not:

```vim
Plugin 'scrooloose/nerdcommenter'
Plugin 'markgandolfo/nerdtree-fetch'
```

I recently experienced this with the [`EvanDotPro/nerdtree-chmod`](https://github.com/EvanDotPro/nerdtree-chmod) plugin after I updated to Vim 8.
